language: objective-c  
os: osx  
osx_image: xcode7  
before_install:  
- export LANG=en_US.UTF-8
- brew update
- npm install -g npm@2.14.5
- npm install -g grunt-cli cordova ionic
before_script:  
- ./scripts/decrypt-key.sh
- ./scripts/add-key.sh
script:  
- npm install
- grunt test
- grunt pushCoverage
- ionic platform add ios
- ionic plugin add cordova-plugin-app-version
- ionic plugin add cordova-plugin-network-information
- ionic plugin add ionic-plugin-keyboard
- ionic plugin add cordova-plugin-x-toast
- ionic plugin add phonegap-plugin-push
- ionic build ios --device --release
- ionic build ios --device --release
after_success:  
- ./scripts/package-and-upload.sh
env:  
  global:
  - APP_NAME="BOM"
  - DEVELOPER_NAME="iPhone Distribution: Consultora Eudaimonia SRL (Z4V65GVN5Q)"
  - PROFILE_NAME="BOM_Dist"
  - PROFILE_UUID="ec402d53-39af-4ba7-ac73-ebfcd1169c6e"
  - DELIVER_WHAT_TO_TEST="Nueva version BOM"
  - HOCKEYAPP_UPLOAD_BRANCH="master"
